In [1]:
import pandas as pd
df=pd.read_csv("complete_results.csv")
df

,name,main_category,sub_category,image,link,no_of_ratings,discount_price,actual_price,review_rating,original_review_text,...,t5_rouge1,t5_rouge2,t5_rougeL,t5_avg_rouge,best_model,raw_best_summary,best_avg_score,cleaned_narrative,qwen_used,processing_time_seconds
0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,965,"₹10,999","₹18,999",3.0 out of 5 stars,NOTE:,...,0.000000,0.000000,0.000000,0.000000,BART,WARNING: GRAPHIC CONTENT. CLICK HERE to read t...,0.000000,"""The customer mentioned that while they found ...",True,5.779507
1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,"113,956","₹18,999","₹19,999",1.0 out of 5 stars,Very bad experience with this device xr phone....,...,0.735294,0.727273,0.735294,0.732620,BART,Very bad experience with this device xr phone....,0.867236,The customer mentioned their extremely negativ...,True,4.791277
2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,"90,304","₹1,999","₹2,299",5.0 out of 5 stars,Amazing phone with amazing camera coming from ...,...,0.666667,0.650000,0.666667,0.661111,T5,amazon.com: amazing phone with amazing camera ...,0.661111,"""The customer was thoroughly impressed with th...",True,3.900565
3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,"24,863","₹15,999","₹24,999",1.0 out of 5 stars,So I got the device XR just today. The product...,...,0.564103,0.447368,0.512821,0.508097,T5,the face ID is not working and there's a glitc...,0.508097,The customer mentioned that the Face ID featur...,True,4.366925
4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,"113,956","₹18,999","₹19,999",5.0 out of 5 stars,I've been an android user all my life until I ...,...,0.677165,0.624000,0.661417,0.654194,T5,i've been an android user all my life until I ...,0.654194,The customer mentioned that they were previous...,True,4.871587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5005,"ASUS MD100 Marshmallow/Silent, Adj. DPI, Multi...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61hXCL4uC7...,https://www.amazon.in/ASUS-MD100-Marshmallow-Q...,NaN,"₹1,499","₹2,999",5.0 out of 5 stars,Superbb,...,0.200000,0.000000,0.200000,0.133333,T5,Superbb: superbb! Superb!Superb!superb! superb...,0.133333,The customer mentioned that they are extremely...,True,4.098456
5006,Crysendo Headphone Cushion Pad Compatible with...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51ODZvKNuS...,https://www.amazon.in/Crysendo-Headphone-Compa...,231,₹499,₹849,5.0 out of 5 stars,Nothing,...,0.000000,0.000000,0.000000,0.000000,BART,Nothing. Nothing is nothing. Nothing can be no...,0.063492,"""The customer mentioned, ""Nothing,"" which succ...",True,3.190932
5007,"VOYEE Controller for PC, Wired Gamepad, Gaming...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61E7Kdsa1k...,https://www.amazon.in/VOYEE-Controller-Gamepad...,85,₹699,"₹1,999",4.0 out of 5 stars,NaN,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000
5008,boAt Airdopes 393ANC True Wireless in Ear Earb...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/boAt-Airdopes-393ANC-Wir...,67,"₹2,299","₹4,990",5.0 out of 5 stars,NaN,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000
5009,Quess Care Total Protection Plan for 1 Year Pr...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Quess-Screen-Protection-...,177,₹649,"₹1,249",4.0 out of 5 stars,NaN,...,0.000000,0.000000,0.000000,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000

In [2]:
df.head()

,name,main_category,sub_category,image,link,no_of_ratings,discount_price,actual_price,review_rating,original_review_text,...,t5_rouge1,t5_rouge2,t5_rougeL,t5_avg_rouge,best_model,raw_best_summary,best_avg_score,cleaned_narrative,qwen_used,processing_time_seconds
0,"Redmi 10 Power (Power Black, 8GB RAM, 128GB St...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81eM15lVcJ...,https://www.amazon.in/Redmi-Power-Black-128GB-...,965,"₹10,999","₹18,999",3.0 out of 5 stars,NOTE:,...,0.000000,0.000000,0.000000,0.000000,BART,WARNING: GRAPHIC CONTENT. CLICK HERE to read t...,0.000000,"""The customer mentioned that while they found ...",True,5.779507
1,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM,...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71AvQd3Vzq...,https://www.amazon.in/OnePlus-Nord-Lite-128GB-...,"113,956","₹18,999","₹19,999",1.0 out of 5 stars,Very bad experience with this device xr phone....,...,0.735294,0.727273,0.735294,0.732620,BART,Very bad experience with this device xr phone....,0.867236,The customer mentioned their extremely negativ...,True,4.791277
2,OnePlus Bullets Z2 Bluetooth Wireless in Ear E...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51UhwaQXCp...,https://www.amazon.in/Oneplus-Bluetooth-Wirele...,"90,304","₹1,999","₹2,299",5.0 out of 5 stars,Amazing phone with amazing camera coming from ...,...,0.666667,0.650000,0.666667,0.661111,T5,amazon.com: amazing phone with amazing camera ...,0.661111,"""The customer was thoroughly impressed with th...",True,3.900565
3,"Samsung Galaxy M33 5G (Mystique Green, 6GB, 12...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/81I3w4J6yj...,https://www.amazon.in/Samsung-Mystique-Storage...,"24,863","₹15,999","₹24,999",1.0 out of 5 stars,So I got the device XR just today. The product...,...,0.564103,0.447368,0.512821,0.508097,T5,the face ID is not working and there's a glitc...,0.508097,The customer mentioned that the Face ID featur...,True,4.366925
4,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/71V--WZVUI...,https://www.amazon.in/OnePlus-Nord-Black-128GB...,"113,956","₹18,999","₹19,999",5.0 out of 5 stars,I've been an android user all my life until I ...,...,0.677165,0.624000,0.661417,0.654194,T5,i've been an android user all my life until I ...,0.654194,The customer mentioned that they were previous...,True,4.871587

In [3]:
df.tail()

,name,main_category,sub_category,image,link,no_of_ratings,discount_price,actual_price,review_rating,original_review_text,...,t5_rouge1,t5_rouge2,t5_rougeL,t5_avg_rouge,best_model,raw_best_summary,best_avg_score,cleaned_narrative,qwen_used,processing_time_seconds
5005,"ASUS MD100 Marshmallow/Silent, Adj. DPI, Multi...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61hXCL4uC7...,https://www.amazon.in/ASUS-MD100-Marshmallow-Q...,NaN,"₹1,499","₹2,999",5.0 out of 5 stars,Superbb,...,0.2,0.0,0.2,0.133333,T5,Superbb: superbb! Superb!Superb!superb! superb...,0.133333,The customer mentioned that they are extremely...,True,4.098456
5006,Crysendo Headphone Cushion Pad Compatible with...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/51ODZvKNuS...,https://www.amazon.in/Crysendo-Headphone-Compa...,231,₹499,₹849,5.0 out of 5 stars,Nothing,...,0.0,0.0,0.0,0.000000,BART,Nothing. Nothing is nothing. Nothing can be no...,0.063492,"""The customer mentioned, ""Nothing,"" which succ...",True,3.190932
5007,"VOYEE Controller for PC, Wired Gamepad, Gaming...","tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/I/61E7Kdsa1k...,https://www.amazon.in/VOYEE-Controller-Gamepad...,85,₹699,"₹1,999",4.0 out of 5 stars,NaN,...,0.0,0.0,0.0,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000
5008,boAt Airdopes 393ANC True Wireless in Ear Earb...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/boAt-Airdopes-393ANC-Wir...,67,"₹2,299","₹4,990",5.0 out of 5 stars,NaN,...,0.0,0.0,0.0,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000
5009,Quess Care Total Protection Plan for 1 Year Pr...,"tv, audio & cameras",All Electronics,https://m.media-amazon.com/images/W/IMAGERENDE...,https://www.amazon.in/Quess-Screen-Protection-...,177,₹649,"₹1,249",4.0 out of 5 stars,NaN,...,0.0,0.0,0.0,0.000000,NaN,NaN,0.000000,No customer review available for this product.,False,0.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5010 entries, 0 to 5009
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   name                     5010 non-null   str
 1   main_category            5010 non-null   str
 2   sub_category             5010 non-null   str
 3   image                    5010 non-null   str
 4   link                     5010 non-null   str
 5   no_of_ratings            4976 non-null   str
 6   discount_price           4740 non-null   str
 7   actual_price             4979 non-null   str
 8   review_rating            5010 non-null   str
 9   original_review_text     5007 non-null   str
 10  bart_summary             5007 non-null   str
 11  bart_rouge1              5010 non-null   float64
 12  bart_rouge2              5010 non-null   float64
 13  bart_rougeL              5010 non-null   float64
 14  bart_avg_rouge           5010 non-null   float64
 15  t5_summary               5007 non-null   str
 16  t5_rouge1                5010 non-null   float64
 17  t5_rouge2                5010 non-null   float64
 18  t5_rougeL                5010 non-null   float64
 19  t5_avg_rouge             5010 non-null   float64
 20  best_model               5007 non-null   str
 21  raw_best_summary         5007 non-null   str
 22  best_avg_score           5010 non-null   float64
 23  cleaned_narrative        5010 non-null   str
 24  qwen_used                5010 non-null   bool
 25  processing_time_seconds  5010 non-null   float64
dtypes: bool(1), float64(10), str(15)
memory usage: 983.5 KB

In [5]:
df.shape

(5010, 26)

In [6]:
df.columns

Index(['name', 'main_category', 'sub_category', 'image', 'link',
       'no_of_ratings', 'discount_price', 'actual_price', 'review_rating',
       'original_review_text', 'bart_summary', 'bart_rouge1', 'bart_rouge2',
       'bart_rougeL', 'bart_avg_rouge', 't5_summary', 't5_rouge1', 't5_rouge2',
       't5_rougeL', 't5_avg_rouge', 'best_model', 'raw_best_summary',
       'best_avg_score', 'cleaned_narrative', 'qwen_used',
       'processing_time_seconds'],
      dtype='str')

In [7]:
df["name"].unique()

<StringArray>
[                                                                         'Redmi 10 Power (Power Black, 8GB RAM, 128GB Storage)',
                                                                 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 6GB RAM, 128GB Storage)',
 'OnePlus Bullets Z2 Bluetooth Wireless in Ear Earphones with Mic, Bombastic Bass - 12.4 Mm Drivers, 10 Mins Charge - 20 Hrs...',
 'Samsung Galaxy M33 5G (Mystique Green, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus | Travel Adapte...',
                                                                'OnePlus Nord CE 2 Lite 5G (Black Dusk, 6GB RAM, 128GB Storage)',
                                                                        'Redmi 10 Power (Sporty Orange, 8GB RAM, 128GB Storage)',
 'boAt Airdopes 141 Bluetooth Truly Wireless in Ear Earbuds with mic, 42H Playtime, Beast Mode(Low Latency Upto 80ms) for Ga...',
                                                                    'Apple 20W USB-C Power Adapter (for iPhone, iPad & AirPods)',
  'Fire-Boltt Ninja Call Pro Plus 1.83" Smart Watch with Bluetooth Calling, AI Voice Assistance, 100 Sports Modes IP67 Ratin...',
 'Samsung Galaxy M33 5G (Emerald Brown, 6GB, 128GB Storage) | 6000mAh Battery | Upto 12GB RAM with RAM Plus | Travel Adapter...',
 ...
 'Ytm 10 Pcs (5 Pair) for Samsung Level u Earbuds | Earbuds for Samsung Level U &U2 | Replacement Black Original Earbuds | P...',
 'Zebronics ZEB-BT701RUCF Wireless Bluetooth Multimedia Speaker With Supporting AC3 Audio, SD Card, USB, AUX, FM & Remote Co...',
 'TANTRA BLUEME Car Bluetooth Device with Mic 5.0 - Aux to Bluetooth Converter, Bluetooth Receiver for Home Theatre, Bluetoo...',
 'proffisy 12A Toner Cartridge for HP 12A Q2612A High Yield Compatible for HP Laserjet M1005 MFP,1020,1010/1012/1018/1022/10...',
 'ORICO 2.5 inch USB C Hard Drive Enclosure USB 3.1 Gen 2 to SATA III External Hard Drive Case for SSD HDD 9.5 7mm Tool-Free...',
 'Aroma® NB119 Carter Pro Bluetooth Wireless In Ear Neckband with Long Lasting Playtime 48 Hrs, Smart Voice Assistant, Dual ...',
 'ASUS MD100 Marshmallow/Silent, Adj. DPI, Multi-Mode, with Solar Cover Wireless Optical Mouse (2.4GHz Wireless, Bluetooth, ...',
 'Crysendo Headphone Cushion Pad Compatible with Mi Super Bass Wireless Headphones | 75mm X 60mm Replacement Headset Ear Cus...',
   'VOYEE Controller for PC, Wired Gamepad, Gaming Controller Compatible with PS3/PC Windows 10/8/7, with Dual Vibration Motors',
             'Quess Care Total Protection Plan for 1 Year Protection for Mobile - Price Between 10001 to 15000 (Email Delivery)']
Length: 4613, dtype: str